name: Process Docx Files

on:
  push:
    paths:
      - 'legal_docs/**'

jobs:
  process-docx:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-docx

      - name: Debug: List files in legal_docs
        run: |
          echo "Files in legal_docs:"
          ls -la legal_docs/
